---
- hosts: 172.31.14.132
  become: True
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: Install Git
      yum:
        name: git
        state: present
    - name: Install static website from git
      git:
        repo: https://github.com/javahometech/javahome-app
        dest: /var/www/html
      notify:
        - Restart apache
      tags:
        - deploy
    - name: Start and enable apache
      service:
        name: httpd
        state: started
        enabled: yes
      tags:
        - start
    - name: Change default port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 9090
      notify:
        - Restart apache
  handlers:
    - name: Restart apache
      service:
        name: httpd
        state: restarted
...
